### ISSUE TITLE
Lab Report 2 Feedback

### ISSUE THREAD

**Issue by Amaar-V** [zhh02/CSE15L-lab-reports#2]
**Bug/Input 1**
- [ ] Commit screenshot for bug/input 1
  - Image does not load
- [x] Link to test file for bug/input 1
- [ ] Symptom shown as command + output for bug/input 1
  - Image does not load
- [x] Description of relationship between bug, symptom, and input for bug/input 1

**Bug/Input 2**
- [ ] Commit screenshot for bug/input 2
  - Image does not load
- [x] Link to test file for bug/input 2
- [ ] Symptom shown as command + output for bug/input 2
  - Image does not load
- [x] Description of relationship between bug, symptom, and input for bug/input 2

**Bug/Input 3**
- [ ] Commit screenshot for bug/input 3
  - Image does not load
- [x] Link to test file for bug/input 3
- [ ] Symptom shown as command + output for bug/input 3
  - Image does not load
- [x] Description of relationship between bug, symptom, and input for bug/input 3

Additional comments from your grader:
**Great Job!**
*Please comment on this issue if you have any questions or need clarification, thanks!*

Feel free to comment below if you have any questions about the rubric/feedback.

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by zhh02** [comment]
Thank you for your feedback Amaar! I realized that my images are not loading because I used the full URL links and I got this fixed by replacing the links with the file names.

**Comment by Amaar-V** [comment]
No problem! Great job fixing the links.

**Comment by Amaar-V** [comment]
Well Done!
